name: Build Android APK
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Update to v4 for consistency
      - name: Set up JDK
        uses: actions/setup-java@v4  # Update to v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: android-actions/setup-android@v3  # Update to v3
      - name: Build APK
        run: ./gradlew assembleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v4  # Fix: Use v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk